services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: <Password>
      database__connection__database: ghost
      url: <Url>
    volumes:
      - ./data/ghost:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
    volumes:
      - ./data/db:/var/lib/mysql

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token <Token>
    restart: unless-stopped