apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-spworlds-city-deployment
  namespace: minecraft
  labels:
    app: mc-spworlds-city
spec:
  selector:
    matchLabels:
      app: mc-spworlds-city
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-spworlds-city
    spec:
      containers:
        - name: mc-spworlds-city-container
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.20.1"
            - name: TYPE
              value: "PAPER"
            - name: MEMORY
              value: "3G"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: mc-spworlds-city-storage
              mountPath: "/data"
      volumes:
        - name: mc-spworlds-city-storage
          nfs:
            server: nfs-server-ip
            path: nfs-server-paht
---
apiVersion: v1
kind: Service
metadata:
  name: mc-spworlds-city-service-nodeport
  namespace: minecraft
spec:
  selector:
    app: mc-spworlds-city
  type: NodePort
  ports:
    - name: game-port
      port: 25565
      nodePort: 32000
      protocol: TCP
