services:
  database:
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data/db/:/var/lib/postgresql/data/
      - ./data/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: <Password>
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token <Token>
    restart: unless-stopped
